//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartingFresh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilestoneModel
    {
        public int MilestoneId { get; set; }
        public string Description { get; set; }
        public System.DateTime EndDate { get; set; }
        public string EndDateString { get; set; }
        public System.DateTime StartTime { get; set; }
        public string StartTimeString { get; set; }
        public int TotalProjectDays { get; set; }
        public bool ResetStartDate { get; set; }
    }
}
